version: '3.8'

services:
  redis:
    image: redis:alpine
  # celery:
  #   build: ./canon_transcribe
  #   command: celery -A core worker -l info
  #   volumes:
  #     - ./canon_transcribe/:/usr/src/app/
  #   environment:
  #     - DEBUG=1
  #     - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
  #     - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
  #   depends_on:
  #     - redis
  # celery-beat:
  #   build: ./canon_transcribe
  #   command: celery -A core beat -l info
  #   volumes:
  #     - ./canon_transcribe/:/usr/src/app/
  #   environment:
  #     - DEBUG=1
  #     - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
  #     - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
  #   depends_on:
  #     - redis